### ISSUE TITLE
Start building example ConTeXt document again

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#575]
To unblock the release of Markdown 3.11.4, we stopped building the example ConTeXt document in commit https://github.com/Witiko/markdown/commit/d4c00548b627eaa8022e7bc278b7a8f5bfb6c6eb, as discussed with @gucci-on-fleek in https://github.com/gucci-on-fleek/context-packaging/issues/2. Even after that commit, the tests [seem broken](https://github.com/Witiko/markdown/actions/runs/15857751796/job/44708712616). For the next release, a proper fix would be welcome.

**Comment by gucci-on-fleek** [comment]
Running `mtxrun --generate` and `mtxrun --luatex --generate` after running `texhash` should fix this, or you can wait until tomorrow for the [`2025-06-12-14-21-B`](https://github.com/gucci-on-fleek/context-packaging/releases/tag/2025-06-12-14-21-B) version where this should be fixed.

**Comment by Witiko** [comment]
Thanks, @gucci-on-fleek, for the fast response, it's much appreciated!

I reverted commit d4c00548b627eaa8022e7bc278b7a8f5bfb6c6eb in commit 6fbd4dc7 and I started running `mtxrun --luatex --generate` in `Dockerfile` after commit ccf580ba216395e7ec364ba2b44847e189307753. After [the CI](https://github.com/Witiko/markdown/actions/runs/15871828530) has successfully finished, we can close this ticket.

**Comment by Witiko** [comment]
This is somewhat unrelated but does the following patch from [islandoftex/images/texlive!30](https://gitlab.com/islandoftex/images/texlive/-/issues/30) still apply?

https://github.com/Witiko/markdown/blob/0ae68a6cef42d7c8ade1f0f94360d8f2acd575ae/Dockerfile#L327-L328

If so, then we may want to remove the patch both here and in [islandoftex's Dockerfile](https://gitlab.com/islandoftex/images/texlive/-/blob/master/Dockerfile?ref_type=heads#L77-L78).

**Comment by Witiko** [comment]
> After [the CI](https://github.com/Witiko/markdown/actions/runs/15872261022) has successfully finished, we can close this ticket.

It doesn't seem fixed, the compilation still fails on line 196 of our `Dockerfile` with the same error as in the MWE from https://github.com/gucci-on-fleek/context-packaging/issues/2:

https://github.com/Witiko/markdown/blob/a5230ccb1d4aa18d4b6509a7e415d52b40b065af/Dockerfile#L183-L196

![Image](https://github.com/user-attachments/assets/c74ea10e-367a-45b3-92cf-eeddcbb586ba)

No worries, though. If the update of ConTeXt fixes it, then we can just wait.

**Comment by gucci-on-fleek** [comment]
@Witiko 

> The compilation still fails on line 196 of our `Dockerfile` with the same error as in [gucci-on-fleek/context-packaging#2](https://github.com/gucci-on-fleek/context-packaging/issues/2):
>
> https://github.com/Witiko/markdown/blob/a5230ccb1d4aa18d4b6509a7e415d52b40b065af/Dockerfile#L183-L196
>
> ![Image](https://github.com/user-attachments/assets/c74ea10e-367a-45b3-92cf-eeddcbb586ba)

Hmm, interesting. The log file shows that it's properly indexing `$TEXMFLOCAL`

https://github.com/Witiko/markdown/actions/runs/15871571343/job/44749308350#step:3:5385

```log
#11 97.49 resolvers       | files | file locator '/usr/local/texlive/texmf-local' found as '/usr/local/texlive/texmf-local'
#11 97.49 resolvers       | resolving | hash '/usr/local/texlive/texmf-local' appended
[...]
#11 99.86 resolvers       | resolving | saving tree '/usr/local/texlive/texmf-local'
#11 99.86 resolvers       | caches | hashing tree '/usr/local/texlive/texmf-local', hash '1f08e3a96247a4bd25d903ca1cb00c0e'
#11 99.86 resolvers       | caching | preparing 'files' for '/usr/local/texlive/texmf-local'
#11 99.86 resolvers       | caching | category 'files', cachename '/usr/local/texlive/texmf-local' saved in '/usr/local/texlive/2025/texmf-var/luametatex-cache/context/a86c089b384a3076dc514ba966a1fac9/trees/1f08e3a96247a4bd25d903ca1cb00c0e.lua'
```

And on my local system, a similar test seems to work correctly:

```console
$ mkdir -p $(kpsewhich --var-value=TEXMFLOCAL)/tex/testing/markdown/

$ echo 'Hello, world!' > $(kpsewhich --var-value=TEXMFLOCAL)/tex/testing/markdown/markdown-test.tex

$ mtxrun --generate
[...]

$ mtxrun --find-file markdown/markdown-test
/usr/local/texlive/texmf-local/tex/testing/markdown/markdown-test.tex

$ tlmgr info context
package:     context
[...]
cat-version: 2025-06-12 14:21 A
[...]
```

So hopefully the `2025-06-12 14:21 B` update fixes this, but if not, I'll investigate further.

**Comment by Witiko** [comment]
While the issue was [fixed][1] using the `texlive/texlive:latest` Docker image from last Saturday with ConTeXt `2025-06-12 14:21 B`, it [reappeared][2] in the Docker image from this Saturday with ConTeXt `2025-07-04 21:26 A`.

Both CI builds are from the same commit d4422be, which should eliminate most potential causes other than ConTeXt.

I am reopening this ticket and pinging @gucci-on-fleek.

 [1]: https://github.com/Witiko/markdown/actions/runs/16098562930/job/45424679448
 [2]: https://github.com/Witiko/markdown/actions/runs/16113128709/job/45461055521

**Comment by gucci-on-fleek** [comment]
@Witiko 

> While the issue was [fixed](https://github.com/Witiko/markdown/actions/runs/16098562930/job/45424679448) using the `texlive/texlive:latest` Docker image from last Saturday with ConTeXt `2025-06-12 14:21 B`, it [reappeared](https://github.com/Witiko/markdown/actions/runs/16113128709/job/45461055521) in the Docker image from this Saturday with ConTeXt `2025-07-04 21:26 A`.

Whoops, looks like I missed testing with MkIV (which is where the action is failing). This should be fixed in gucci-on-fleek/context-packaging@97fb11157e860d575fecab84e76195b9e45d57d7, and since there was an upstream ConTeXt released earlier today, this fix will be contained in the update automatically pushed to CTAN tonight. Thanks again for the report.

**Comment by gucci-on-fleek** [comment]
@Witiko 

> Also, this is a bit unrelated but does the following patch from [islandoftex/images/texlive#30](https://gitlab.com/islandoftex/images/texlive/-/issues/30) still apply?
> 
> [...]
>
> If so, then we may want to remove the patch both here and in [islandoftex's Dockerfile](https://gitlab.com/islandoftex/images/texlive/-/blob/master/Dockerfile?ref_type=heads#L77-L78).

Looks like that patch is still needed:

```console
$ sudo tlmgr path add

$ export PATH=/usr/local/bin/:/usr/bin/

$ mtxrun --generate
resolvers       | resolving | variable 'SELFAUTOLOC' set to '/usr/local/bin'
resolvers       | resolving | variable 'SELFAUTODIR' set to '/usr/local'
resolvers       | resolving | variable 'SELFAUTOPARENT' set to '/usr'
resolvers       | resolving | variable 'TEXMFCNF' set to ''
resolvers       | resolving | variable 'TEXMF' set to ''
resolvers       | resolving | variable 'TEXOS' set to 'local'
resolvers       | resolving |
resolvers       | resolving | using configuration specification 'home:texmf/web2c;selfautoparent:/texmf-local/web2c;selfautoparent:/texmf-context/web2c;selfautoparent:/texmf/web2c'
resolvers       | resolving |
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/home/max/texmf/web2c' from specification 'home:texmf/web2c'
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/usr/texmf-local/web2c' from specification 'selfautoparent:/texmf-local/web2c'
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/usr/texmf-context/web2c' from specification 'selfautoparent:/texmf-context/web2c'
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/usr/texmf/web2c' from specification 'selfautoparent:/texmf/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/home/max/texmf/web2c' from specification 'home:texmf/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/usr/texmf-local/web2c' from specification 'selfautoparent:/texmf-local/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/usr/texmf-context/web2c' from specification 'selfautoparent:/texmf-context/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/usr/texmf/web2c' from specification 'selfautoparent:/texmf/web2c'
resolvers       | resolving |
resolvers       | resolving | warning: no lua configuration files found
resolvers       | resolving | no texmf paths are defined (using TEXMF)
resolvers       | resolving |
mtxrun          |
mtxrun          | elapsed lua time: 0.008 seconds

$ context --once --nofile
mtxrun          | forcing cache reload
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/home/max/texmf/web2c' from specification 'home:texmf/web2c'
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/usr/texmf-local/web2c' from specification 'selfautoparent:/texmf-local/web2c'
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/usr/texmf-context/web2c' from specification 'selfautoparent:/texmf-context/web2c'
resolvers       | resolving | looking for regular 'texmfcnf.lua' on given path '/usr/texmf/web2c' from specification 'selfautoparent:/texmf/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/home/max/texmf/web2c' from specification 'home:texmf/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/usr/texmf-local/web2c' from specification 'selfautoparent:/texmf-local/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/usr/texmf-context/web2c' from specification 'selfautoparent:/texmf-context/web2c'
resolvers       | resolving | looking for fallback 'contextcnf.lua' on given path '/usr/texmf/web2c' from specification 'selfautoparent:/texmf/web2c'
resolvers       | resolving |
resolvers       | resolving | warning: no lua configuration files found
resolvers       | resolving | no texmf paths are defined (using TEXMF)
resolvers       | resolving |
mtxrun          | the resolver databases are not present or outdated
resolvers       | resolving | using suffix based filetype 'lua'
resolvers       | resolving | remembering file 'mtx-context.lua' using hash 'lua::mtx-context.lua'
resolvers       | resolving | using suffix based filetype 'lua'
resolvers       | resolving | remembering file 'mtx-contexts.lua' using hash 'lua::mtx-contexts.lua'
resolvers       | resolving | remembered file 'mtx-context.lua'
resolvers       | resolving | using suffix based filetype 'lua'
resolvers       | resolving | remembering file 'mtx-t-mtx-context.lua' using hash 'lua::mtx-t-mtx-context.lua'
resolvers       | resolving | using suffix based filetype 'lua'
resolvers       | resolving | remembering file 'mtx-t-mtx-contexts.lua' using hash 'lua::mtx-t-mtx-contexts.lua'
resolvers       | resolving | remembered file 'mtx-t-mtx-context.lua'
resolvers       | resolving | remembered file 'mtx-context.lua'
mtxrun          | unknown script 'mtx-context.lua' or 'mtx-mtx-context.lua'
```

I'll look into that to see if I can figure out a proper fix.

**Comment by Witiko** [comment]
@gucci-on-fleek: As seen today in our `texlive/texlive:latest-minimal`-based Docker image produced earlier today in [this workflow](https://github.com/Witiko/markdown/actions/runs/17068377502/job/48391015358), there seem to be issues with generating the ConTeXt MkIV format for LuaTeX:

```
witiko@witiko-G5-5590:~$ docker run --rm -it ghcr.io/witiko/markdown:3.11.4-51-gc057f57a-latest-minimal-no_docs
root@36937136173e:/workdir# context --luatex --make
```
```
[...]

system          > lua > loading of file '/usr/local/texlive/2025/texmf-dist/tex/context/base/mkiv/trac-vis.lua' failed:
	no message
resolvers       > lua > loading file '/usr/local/texlive/2025/texmf-dist/tex/context/base/mkiv/trac-vis.lua' failed

error loading file: trac-vis.lua (aborting)resolvers       | formats |
resolvers       | formats | binary path      : /usr/local/texlive/2025/bin/x86_64-linux
resolvers       | formats | format path      : /usr/local/texlive/2025/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex
resolvers       | formats | luatex engine    : luatex
resolvers       | formats | lua startup file : /usr/local/texlive/2025/texmf-dist/tex/context/base/mkiv/luat-cod.lua
resolvers       | formats | context file     : /usr/local/texlive/2025/texmf-dist/tex/context/base/mkiv/cont-en.mkiv
resolvers       | formats | run time         : 1.110 seconds
resolvers       | formats | return value     : okay
resolvers       | formats |
system          | total runtime: 1.245 seconds
```
```
root@36937136173e:/workdir# ls /usr/local/texlive/2025/texmf-var/luatex-cache/context/a86c089b384a3076dc514ba966a1fac9/formats/luatex
```
```
cont-en.log
```
```
root@36937136173e:/workdir# texlua /usr/local/texlive/2025/texmf-dist/tex/context/base/mkiv/trac-vis.lua
```
```
...xlive/2025/texmf-dist/tex/context/base/mkiv/trac-vis.lua:1503: too many local variables (limit is 200) in main function near '('
```

Roughly, the image is build from `texlive/texlive:latest-minimal` with the following commands:

```
tlmgr update --self --all
tlmgr install context
sed -i '/package.loaded\["data-ini"\]/a if os.selfpath then environment.ownbin=lfs.symlinktarget(os.selfpath..io.fileseparator..os.selfname);environment.ownpath=environment.ownbin:match("^.*"..io.fileseparator) else environment.ownpath=kpse.new("luatex"):var_value("SELFAUTOLOC");environment.ownbin=environment.ownpath..io.fileseparator..(arg[-2] or arg[-1] or arg[0] or "luatex"):match("[^"..io.fileseparator.."]*$") end' /usr/bin/mtxrun.lua
mtxrun --generate
texlua /usr/bin/mtxrun.lua --luatex --generate
context --make
context --luatex --make
```

However, I haven't been able to reproduce it manually thus far. Therefore, I disabled the ConTeXt tests in commit 425e3a86324a579fc6bf6e8ea20658a05ba35c42 from PR https://github.com/Witiko/markdown/pull/569, hopefully temporarily.
